tasks:
  - init: npm install
    command: 
      export HMR_HOST=`gp url 5173`
      echo "Starting development server at $HMR_HOST"
      npm run dev

ports:
  - port: 5173
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode